hdk

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,24 +1,32 @@
 #!bin/bash
 IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
-git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b gcc9-20190329 gcc
-git clone https://github.com/najahiiii/dragontc.git -b 9.0 clang
-GCC="$(pwd)/gcc/bin/aarch64-linux-gnu-"
-CT="$(pwd)/clang/bin/clang"
-TZ="Asia/Jakarta"
-curl -s -F chat_id=-1001429218403 -F sticker="CAADBQAD7wADQxCzIs_rqaRTwvagAg" https://api.telegram.org/bot826431581:AAFRriNDLlXyNVi9NvnH4cGC7XUPdeRkW10/sendSticker
-curl -s -X POST https://api.telegram.org/bot826431581:AAFRriNDLlXyNVi9NvnH4cGC7XUPdeRkW10/sendMessage?chat_id=-1001429218403 -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>WinXKernel</b> building"'!'"%0AFor device <b>RIVA</b> (Redmi 5A)%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0ACompiler <code>$(${GCC}gcc --version | head -n 1)</code>%0AClang <code>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</code>%0AStarted on <code>$(date)</code>%0A<b>Build Status:</b> #untested"
+git clone https://github.com/najahiiii/clang.git -b llvm9 llvm9
+CT="$(pwd)/llvm9/bin/clang"
+CLANG_TRIPLE=aarch64-linux-gnu-
+CLANG_LD=aarch64-linux-gnu-ld.gold
+curl -s -F chat_id=-1001429218403 -F sticker="CAADBQADIwAD7bkQKyMZ6Vhta9h8Ag" https://api.telegram.org/bot826431581:AAFRriNDLlXyNVi9NvnH4cGC7XUPdeRkW10/sendSticker
+curl -s -X POST https://api.telegram.org/bot826431581:AAFRriNDLlXyNVi9NvnH4cGC7XUPdeRkW10/sendMessage?chat_id=-1001429218403 -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>WinX Kernel</b> building"'!'"%0AFor device <b>RIVA</b> (Redmi 5A)%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0AClang <code>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</code>%0AStarted on <code>$(date)</code>%0A<b>Build Status:</b> #untested%0A<b>Semaphore CI Build Info</b> - <a href='https://semaphoreci.com/fauzandhiyaul/winxkernel'>Status</a>"
 tanggal=$(date +'%H%M-%d%m%y')
 START=$(date +"%s")
-export TZ
 export ARCH=arm64
 export KBUILD_BUILD_USER=FauzanDF
-export KBUILD_BUILD_HOST=SemaphoreCI
+export CLANG_TRIPLE
+export CLANG_LD
 export USE_CCACHE=1
 export CACHE_DIR=~/.ccache
-# Function to upload to sprunge
+# Function to upload to ix.io
 function sprunge() {
     cat build.log | curl -F 'sprunge=<-' http://sprunge.us > link
     HASIL="$(cat link)"
+}
+# Function to upload to del.dog
+function deldog() {
+    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
+        echo "ERROR: failed to post document" >&2
+        exit 1
+    }
+    KEY=$(jq -r .key <<< "${RESULT}")
+    echo "https://del.dog/raw/${KEY}"
 }
 # Fin Error
 function finerr() {
@@ -27,7 +35,7 @@ function finerr() {
         exit 1
 }
 make -s -C $(pwd) O=out riva-perf_defconfig
-make -s -C $(pwd) CC=${CT} CROSS_COMPILE=${GCC} O=out -j32 -l12 2>&1| tee build.log
+make -s -C $(pwd) CC=${CT} O=out -j6 -l8 2>&1| tee build.log
 if ! [ -a $IMAGE ]; then
 	finerr
 	exit 1
